In [3]:
import pandas as pd

## Series: 
 ### A panda  series is a one dimensional array-like an object that can hold any data type. It is similar to a column in table.

In [4]:
import pandas as pd
data = [1,2,3,4,5]
series = pd.Series(data)
print("Series \n", series)

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
## Create a Series from Dictionary
data = {'a':1, 'b':2, 'c':3}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [6]:
data =[36, 38, 42]
index=["Abhi", "Shristy", "Arpit"]
pd.Series(data, index = index)

Abhi       36
Shristy    38
Arpit      42
dtype: int64

## DataFrame

In [7]:
## Create a DataFrame from a dictionary of List
data={
    'Name': ["Arpit","Shristy","Abhishek"],
    'RollNo': [42, 38, 36],
    'District': ["Bhojpur", "Rohtas", "Patna"]
}
index = [1, 2, 3]
df = pd.DataFrame(data, index = index)
print(df)
print(type(df))

       Name  RollNo District
1     Arpit      42  Bhojpur
2   Shristy      38   Rohtas
3  Abhishek      36    Patna
<class 'pandas.DataFrame'>

In [8]:
import numpy as np
np.array(df)

array([['Arpit', 42, 'Bhojpur'],
       ['Shristy', 38, 'Rohtas'],
       ['Abhishek', 36, 'Patna']], dtype=object)

In [9]:
## Create a DataFrame from a list of Dictionaries

data = [
    {'Name': "Arpit", 'RollNo': 42, "District": "Bhojpur"},
    {'Name': "Shristy", 'RollNo': 38, "District": "Rohtas"},
    {'Name': "Abhi", 'RollNo': 36, "District": "Patna"},
]
df = pd.DataFrame(data)
print(df)
print(type(df))

      Name  RollNo District
0    Arpit      42  Bhojpur
1  Shristy      38   Rohtas
2     Abhi      36    Patna
<class 'pandas.DataFrame'>

In [10]:
df = pd.read_csv('sales_data.csv')
df.head(3)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card

In [11]:
df.tail(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [12]:
## Accessing Data From DataFrame
df = pd.DataFrame(data)

In [13]:
df

      Name  RollNo District
0    Arpit      42  Bhojpur
1  Shristy      38   Rohtas
2     Abhi      36    Patna

In [14]:
type(df['Name'])

pandas.Series

In [15]:
df.loc[0]

Name          Arpit
RollNo           42
District    Bhojpur
Name: 0, dtype: object

In [16]:
df.iloc[0]['Name']

'Arpit'

In [17]:
## Accessing a specified element
df.at[1, 'Name']

'Shristy'

In [18]:
## Accessing a specific element using iat
df.iat[0,0]

'Arpit'

In [19]:
df

      Name  RollNo District
0    Arpit      42  Bhojpur
1  Shristy      38   Rohtas
2     Abhi      36    Patna

In [ ]:
''' Data Manipulation with Dataframe'''
## Adding a column
df['CGPA'] =[6.95, 8.15, 8.15]
df

      Name  RollNo District  CGPA
0    Arpit      42  Bhojpur  6.95
1  Shristy      38   Rohtas  8.15
2     Abhi      36    Patna  8.15

In [21]:
## Remove a Column
df.drop('District', axis =1, inplace = True)
df

      Name  RollNo  CGPA
0    Arpit      42  6.95
1  Shristy      38  8.15
2     Abhi      36  8.15